# Generated by Django 4.2.3 on 2023-08-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_priority_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Study', 'Study'), ('Home', 'Home'), ('Health', 'Health'), ('Shopping', 'Shopping'), ('Social', 'Social'), ('Finance', 'Finance'), ('Travel', 'Travel'), ('Hobbies', 'Hobbies')], max_length=50),
        ),
    ]
